server:
  port: 8080
  servlet:
    context-path: /
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp 
            
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/dabang?serverTimezone=Asia/Seoul
    username: dabang
    password: bitc5600
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      com.mysql.cj.jdbc.Driver
#  jdbc:log4jdbc:mysql://localhost:3306/dabang?serverTimezone=Asia/Seoul
    
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB    
      
file:
  path: C:/src/springbootProject/dabwang/media/
  
  
  
  